server:
  port: 8080
  shutdown: graceful

spring:
  output:
    ansi:
      enabled: always
  mvc:
    path match:
      matching-strategy: ant_path_matcher
    static-path-pattern: /static/**  # 특수 문자(@,.)로 의한 이메일 정적리소스 처리되는 것을 막기 위한 정적 리소스 요청 패턴 명시.

  profiles:
    active: build

  spring:
    http:
      encoding:
        charset: UTF-8
        enabled: true
        force: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 10
        dialect: org.hibernate.dialect.MySQLDialect

  datasource:
    url: jdbc:mysql://localhost:3306/team6?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: root
    password: 1234
    hikari:
      auto-commit: false

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE
